steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/thematic-coda-381718/listen-link', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/thematic-coda-381718/listen-link']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'listenlink', '--image', 'gcr.io/thematic-coda-381718/listen-link', '--region', 'us-east1', '--platform', 'managed']
images:
- gcr.io/thematic-coda-381718/listen-link